[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npx prisma db seed && npm start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
